POST http://localhost:3001/api/cards
Content-Type: application/json

{
  "question": "kysymys2",
  "courseId": "62064823dc53e2c2bff3bef5",
  "partId": "62064831dc53e2c2bff3befa",
  "answers": [
    { "id": 1, "answer": "p" },
    { "id": 2, "answer": "p" },
    { "id": 3, "answer": "p" },
    { "id": 4, "answer": "p" }
  ],
  "correctAnswerId": "2"
}

    