POST http://localhost:3001/api/answers
Content-Type: application/json

{
    "content": "on mikä tahansa tilastollinen testi, joka noudattaa Spearmanin t-jakaumaa kun vaihtoehtoinen hypoteesi ei ole voimassa",
    "correctAnswer": false
}
    