POST http://localhost:3001/api/questions
Content-Type: application/json

{
	"content": "Oikeudellisen ratkaisun teoria on",
	"courseId": "63d00604c5e23b0997d7898d",
	"questiontype": "monivalinta",
	"answers": [{
		"correctAnswer": true,
		"content": "sekä käytännön lainsoveltamisen että oikeustieteellisen opetuksen ja tutkimuksen työväline"
	},{
		"correctAnswer": false,
		"content": "käytännön lainsoveltamisen työväline mutta ei oikeustieteellisen opetuksen ja tutkimuksen työväline"
	},{
		"correctAnswer": false,
		"content": "opetuksen ja tutkimuksen työväline, mutta ei käytännön lainsoveltamisen työvälinen"
	}]
}

    