POST http://localhost:3001/api/cards
Content-Type: application/json

{
    "courseId": "2",
    "partId": "1",
    "QAndA": {
        "question": "Aivokuori vastaa...",
        "answers": [
            {
                "id": 1, 
                "answer": "autonomisen hermoston säätelystä"
            },
            {
                "id": 2, 
                "answer": "tunteiden hallinnasta"
            },
            {
                "id": 3, 
                "answer": "taistele tai pakene -reaktion synnyttämisestä"
            },
            {
                "id": 4, 
                "answer": "tunnekokemusten heräämisestä"
            }
        ],
        "correctAnswerId": 2
    }
    
}