POST http://localhost:3001/api/treeNodes
Content-Type: application/json

{
  "name": "Ekan luvun toisen alaluvun alaluku",
  "description": "asdf",
  "course": "63ce87c397e8871b0a8e6b61",
  "parent": "63ce8dc497e8871b0a8e6bb6", 
  "questions": ["63ce88a897e8871b0a8e6b6a", "63ce88d897e8871b0a8e6b6d"]
}